### ISSUE TITLE
Forestry and Railcraft liquids don't respect Bucketnerf

### ISSUE THREAD

**Issue by tyrael93** [makamys/BucketNerf#3]
Hello, it's me again bothering you again about some minor inconsistencies with this wonderful mod that I can't still thank you enough for.

Shameless asskissing aside, I went on a blacklisting spree to remove what fluids could actually be placed outside of water and if they could still irrigate farmland, which to my surprise was basically all of them. When I tested in my world, apparently forestry's fluids either didn't seem to register, or ignored the commands altogether. I've tested this with both the "actual" buckets (so for example for honey Forestry:bucketHoney and for creosote Railcraft:fluid.creosote.bucket) and their gregtech versions. While I blacklisted all of them, both the GT buckets and the forestry/railcraft buckets seemed to ignore the calls. I tested with both netherlicious (spectral dew, both from a regular iron bucket and a GT bucket) and growthcraft (cream bucket, again both growthcraft and GT), and even camelia oil from AMT. Those actually followed the config with no issue. Considering that the railcraft and forestry fluids don't actually have a sound when poured, I think it might be somehow related to them having different hooks compared to the regular forge ones, but I'm mostly talking out of my ass here.

Here's a pic of the configs, just in case I did a goof of sorts.
![image](https://user-images.githubusercontent.com/5557920/198839115-c404d457-d316-412d-83e3-6d39e3540fba.png)

Thank you in advance as always and feel free to throw a shoe at me at your earliest convenience for pestering you with all these bugfixes :heart:

**Comment by makamys** [comment]
Your suspicion is correct, those mods use custom code for placing liquids which doesn't fire the `FillBucketEvent`, which is what's used to cancel liquid placement when `disableBucketEmptying` is true. But if I set it to false (which causes the `PlayerInteractEvent` to also get cancelled), it works fine. Is there any reason you have it set to true?

**Comment by tyrael93** [comment]
Oh, I thought that was the option that made it so you don't accidentally empty it when interacting with greg tanks and machines and stuff like the mixing/bathing pot when you right click on a wall or something.

**Comment by makamys** [comment]
> Oh, I thought that was the option that made it so you don't accidentally empty it [...] when you right click on a wall or something.

No, you can accomplish that either way by not specifying a second item in the recipe (this is explained in the comment in the config). I guess specifying the same item twice also does the same, but it's kind of weird, and will cause unnecessary stuff to happen like the splash sound to play.

> I really hope you don't get pinged every time I do that

I don't think so (though I was asleep so :shrug:).

**Comment by tyrael93** [comment]
`No, you can accomplish that either way by not specifying a second item in the recipe (this is explained in the comment in the config)`
Oh, I see I am a doofus then
Alright that's even better, thanks!
