### ISSUE TITLE
Mod doesn't work in creative mode

### ISSUE THREAD

**Issue by iamsoNewBee** [makamys/BucketNerf#6]
i redownload my pack and changed mod vision but it doesnt work either (i only load with it when i test)..i think i cant offer more info now because i have no iead why it happened(it used to be normal) 
CAN U USE IT NORMALLY NOW??

**Comment by makamys** [comment]
Well, nothing has changed since January.
Post a log, that's all I can say.

**Comment by iamsoNewBee** [comment]
[2023-06-11-4.log.gz](https://github.com/makamys/BucketNerf/files/11712835/2023-06-11-4.log.gz)

**Comment by iamsoNewBee** [comment]
I guess may the windows or mc1.20 update affected it?it makes no sense

**Comment by makamys** [comment]
That's the wrong kind of log. Add [NotEnoughVerbosity](https://github.com/LegacyModdingMC/NotEnoughVerbosity/releases/) and post `fml-client-latest.log`.

**Comment by iamsoNewBee** [comment]
[fml-client-latest.log](https://github.com/makamys/BucketNerf/files/11712862/fml-client-latest.log)

**Comment by makamys** [comment]
Can't see anything wrong here. Maybe your config is the issue, make sure everything looks fine in `bucketnerf.cfg`.

**Comment by iamsoNewBee** [comment]
any wrong?

**Comment by iamsoNewBee** [comment]
[bucketnerf.txt](https://github.com/makamys/BucketNerf/files/11712872/bucketnerf.txt)

**Comment by iamsoNewBee** [comment]
i truned cfg into txt so i can send it

**Comment by makamys** [comment]
Looks fine. What exactly isn't working? For example, what happens if you right click the ground with a water bucket?

**Comment by iamsoNewBee** [comment]
i send u a video then

**Comment by iamsoNewBee** [comment]
https://cowtransfer.com/s/c5cf0e54103841

**Comment by iamsoNewBee** [comment]
confused?

**Comment by makamys** [comment]
Oh, you're in creative mode. The mod only has an effect in survival mode, this is intentional. (Since the point of creative mode is that you have infinite access to resources.)

**Comment by iamsoNewBee** [comment]
lol
